topconfig disable sis190
disable temporarly sis190 due to build breakage:
drivers/net/sis190.c:329: error: sis190_pci_tbl causes a section type conflict
make[5]: *** [drivers/net/sis190.o] Error 1


git-svn-id: svn://svn.debian.org/svn/kernel/dists/trunk@10272 510b9475-24dd-0310-9b6c-e0eefe99d49f