make comedi x86 only
crap staging driver effecitvely breaks builds on ppc for example:
build/linux-2.6-2.6.29~rc7/debian/build/source_powerpc_none/drivers/staging/comedi/drivers.c: In function 'comedi_buf_alloc':
/build/linux-2.6-2.6.29~rc7/debian/build/source_powerpc_none/drivers/staging/comedi/drivers.c:497: error: 'PAGE_KERNEL_NOCACHE' undeclared (first use in this function)
/build/linux-2.6-2.6.29~rc7/debian/build/source_powerpc_none/drivers/staging/comedi/drivers.c:497: error: (Each undeclared identifier is reported only once
/build/linux-2.6-2.6.29~rc7/debian/build/source_powerpc_none/drivers/staging/comedi/drivers.c:497: error: for each function it appears in.)
make[8]: *** [drivers/staging/comedi/drivers.o] Error 1

git-svn-id: svn://svn.debian.org/svn/kernel/dists/trunk@13072 510b9475-24dd-0310-9b6c-e0eefe99d49f